version: '3'
services:
  app:
    build: .
    container_name: kotlin
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ./gradlew bootRun
  db:
    image: mysql:8.1.0
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent',
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '3306:3306' # ホストの3306が既に使用されているため3307にマッピング
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - TZ=Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
